### ISSUE TITLE
Can't self-play

### ISSUE THREAD

**Issue by Narsil** [dylandjian/SuperGo#1]
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
>     obj = _ForkingPickler.dumps(obj)
>   File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
> TypeError: can't pickle pachi_py.cypachi.PyPachiBoard objects

Environnement virtualenv, python3.6, ubuntu 18.04, pytorch with cuda 9.

Is there a step that I missed ?

**Comment by dylandjian** [comment]
For some reason, pickle doesn't seem to be able to pickle the class instance of pachi_py in Python 3.6.
However it works in Python 3.5, so you have to stick with that !
[Link to a stackoverflow I made with the error](https://stackoverflow.com/questions/49699267/pickle-error-multiprocessing-between-python-3-6-3-and-3-5-2?noredirect=1#comment86411865_49699267)
